from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MeDialog_About_me(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(405, 580)
        Dialog.setWindowIcon(QtGui.QIcon('graduation-hat.png'))
        self.centralwidget = QtWidgets.QWidget(parent=Dialog)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.menubar = QtWidgets.QMenuBar(Dialog)
        self.statusbar = QtWidgets.QStatusBar(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 420, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(125, 99, 32);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 470, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(125, 99, 32);")
        self.label_5.setObjectName("label_5")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(128, 520, 151, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("\n"
"    border-radius: 15px;   \n"
"    border: 2px solid #094065;\n"
"background-color: qlineargradient(spread:pad, x1:0.9899, y1:0.402, x2:0.930348, y2:0.932, stop:0 rgba(202, 214, 229, 255), stop:0.830846 rgba(254, 237, 206, 255));")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(Dialog.close)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 390, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(125, 99, 32);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 450, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(125, 99, 32);")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 261, 381))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Desktop/курсач/About__me.jpg"))
        self.label.setObjectName("label")
        Dialog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Dialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 26))
        self.menubar.setObjectName("menubar")
        Dialog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Dialog)
        self.statusbar.setObjectName("statusbar")
        Dialog.setStatusBar(self.statusbar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("MainWindow", "Обо мне"))
        self.label_3.setText(_translate("MainWindow", "Студентка группы 10701122"))
        self.label_5.setText(_translate("MainWindow", "yulia.kulikovich@gmail.com"))
        self.pushButton_4.setText(_translate("MainWindow", "Назад"))
        self.label_2.setText(_translate("MainWindow", "Автор"))
        self.label_4.setText(_translate("MainWindow", "Куликович Юлия Вячеславовна"))

